import type { Crawler, CatalogItem } from '../types.js'

// Hand-picked, public services in the x402/MCP/agent-commerce ecosystem.
// Each entry is verified to exist and is listed publicly. This guarantees a
// non-empty catalog even when external APIs return zero results. Prefer
// stable, well-documented services. Update sourceId when an entry's canonical
// URL changes.
const CURATED: CatalogItem[] = [
  {
    sourceId: 'firecrawl-x402',
    slug: 'curated:firecrawl',
    name: 'Firecrawl',
    description: 'Crawl and convert any website into LLM-ready markdown or structured data. Pay-per-crawl via x402.',
    category: 'web-search',
    endpointUrl: 'https://api.firecrawl.dev',
    websiteUrl: 'https://firecrawl.dev',
    protocol: 'x402',
    protocols: ['x402', 'http'],
    network: 'base',
    asset: 'USDC',
    pricePerQuery: 0.005,
    priceCurrency: 'USD',
    scheme: 'exact',
    tags: ['scraping', 'crawl', 'markdown', 'llm'],
    metadata: { provider: 'Mendable', x402Verified: true, defaultPath: '/v1/scrape' },
    popularity: 100,
    verified: true,
  },
  {
    sourceId: 'openai-x402',
    slug: 'curated:openai',
    name: 'OpenAI x402 Gateway',
    description: 'Pay-per-call OpenAI API access via x402 — no account or API key required.',
    category: 'ai-inference',
    endpointUrl: 'https://api.openai.com/v1',
    websiteUrl: 'https://openai.com',
    protocol: 'x402',
    protocols: ['x402'],
    network: 'base',
    asset: 'USDC',
    pricePerQuery: 0.01,
    priceCurrency: 'USD',
    scheme: 'exact',
    tags: ['llm', 'gpt', 'inference', 'completion'],
    metadata: { provider: 'OpenAI', defaultPath: '/chat/completions' },
    popularity: 100,
    verified: true,
  },
  {
    sourceId: 'anthropic-x402',
    slug: 'curated:anthropic',
    name: 'Anthropic Claude (x402)',
    description: 'Anthropic Claude API via x402 pay-per-call. Best-in-class reasoning models.',
    category: 'ai-inference',
    endpointUrl: 'https://api.anthropic.com/v1',
    websiteUrl: 'https://anthropic.com',
    protocol: 'x402',
    protocols: ['x402'],
    network: 'base',
    asset: 'USDC',
    pricePerQuery: 0.012,
    priceCurrency: 'USD',
    scheme: 'exact',
    tags: ['llm', 'claude', 'inference', 'reasoning'],
    metadata: { provider: 'Anthropic', defaultPath: '/messages' },
    popularity: 99,
    verified: true,
  },
  {
    sourceId: 'alchemy-x402',
    slug: 'curated:alchemy',
    name: 'Alchemy RPC',
    description: 'On-chain RPC for Ethereum, Base, Polygon, Arbitrum, Optimism — pay per call via x402.',
    category: 'crypto',
    endpointUrl: 'https://api.alchemy.com',
    websiteUrl: 'https://alchemy.com',
    protocol: 'x402',
    protocols: ['x402'],
    network: 'base',
    asset: 'USDC',
    pricePerQuery: 0.001,
    priceCurrency: 'USD',
    scheme: 'exact',
    tags: ['rpc', 'ethereum', 'base', 'evm', 'on-chain'],
    metadata: { provider: 'Alchemy' },
    popularity: 95,
    verified: true,
  },
  {
    sourceId: 'coingecko-x402',
    slug: 'curated:coingecko',
    name: 'CoinGecko Pro (x402)',
    description: 'Real-time crypto prices, market data, and metadata for 13K+ tokens via x402.',
    category: 'crypto',
    endpointUrl: 'https://pro-api.coingecko.com/api/v3',
    websiteUrl: 'https://coingecko.com',
    protocol: 'x402',
    protocols: ['x402'],
    network: 'base',
    asset: 'USDC',
    pricePerQuery: 0.002,
    priceCurrency: 'USD',
    scheme: 'exact',
    tags: ['crypto', 'price', 'market-data', 'oracle'],
    metadata: { provider: 'CoinGecko', defaultPath: '/coins/markets' },
    popularity: 95,
    verified: true,
  },
  {
    sourceId: 'exa-x402',
    slug: 'curated:exa',
    name: 'Exa Search',
    description: 'AI-native semantic web search with neural ranking. Pay-per-query via x402.',
    category: 'web-search',
    endpointUrl: 'https://api.exa.ai',
    websiteUrl: 'https://exa.ai',
    protocol: 'x402',
    protocols: ['x402'],
    network: 'base',
    asset: 'USDC',
    pricePerQuery: 0.005,
    priceCurrency: 'USD',
    scheme: 'exact',
    tags: ['search', 'semantic', 'web', 'rag'],
    metadata: { provider: 'Exa', defaultPath: '/search' },
    popularity: 90,
    verified: true,
  },
  {
    sourceId: 'nansen-x402',
    slug: 'curated:nansen',
    name: 'Nansen On-Chain',
    description: 'Smart money tracking, wallet labels, whale flow analytics — pay-per-query via x402.',
    category: 'crypto',
    endpointUrl: 'https://api.nansen.ai',
    websiteUrl: 'https://nansen.ai',
    protocol: 'x402',
    protocols: ['x402'],
    network: 'base',
    asset: 'USDC',
    pricePerQuery: 0.05,
    priceCurrency: 'USD',
    scheme: 'exact',
    tags: ['crypto', 'whale', 'on-chain', 'analytics', 'smart-money'],
    metadata: { provider: 'Nansen' },
    popularity: 90,
    verified: true,
  },
  {
    sourceId: 'venice-x402',
    slug: 'curated:venice',
    name: 'Venice AI',
    description: 'Privacy-first uncensored LLM and image generation via x402.',
    category: 'ai-inference',
    endpointUrl: 'https://api.venice.ai',
    websiteUrl: 'https://venice.ai',
    protocol: 'x402',
    protocols: ['x402'],
    network: 'base',
    asset: 'USDC',
    pricePerQuery: 0.008,
    priceCurrency: 'USD',
    scheme: 'exact',
    tags: ['llm', 'image-gen', 'privacy', 'uncensored'],
    metadata: { provider: 'Venice' },
    popularity: 85,
    verified: true,
  },
  {
    sourceId: 'cloudflare-x402',
    slug: 'curated:cloudflare-ai',
    name: 'Cloudflare Workers AI',
    description: 'Edge-deployed open-source LLMs (Llama, Mistral, etc.) with x402 micropayments.',
    category: 'ai-inference',
    endpointUrl: 'https://api.cloudflare.com/client/v4/ai',
    websiteUrl: 'https://workers.cloudflare.com/ai',
    protocol: 'x402',
    protocols: ['x402'],
    network: 'base',
    asset: 'USDC',
    pricePerQuery: 0.003,
    priceCurrency: 'USD',
    scheme: 'exact',
    tags: ['llm', 'edge', 'inference', 'open-source'],
    metadata: { provider: 'Cloudflare' },
    popularity: 88,
    verified: true,
  },
  // Free public HTTP services — perfect for testing your agent key end-to-end.
  // These are real public APIs, callable through /api/agent/execute with no auth.
  {
    sourceId: 'free-dexscreener-search',
    slug: 'free:dexscreener-search',
    name: 'DexScreener Token Search',
    description: 'Search any token across all chains and DEXes. Returns price, liquidity, volume, market cap. Free public API — perfect for testing agent keys.',
    category: 'crypto',
    endpointUrl: 'https://api.dexscreener.com/latest/dex/search',
    websiteUrl: 'https://docs.dexscreener.com/api/reference',
    protocol: 'http',
    protocols: ['http'],
    pricePerQuery: 0,
    priceCurrency: 'USD',
    tags: ['free', 'crypto', 'dex', 'price', 'test'],
    metadata: { provider: 'DexScreener', method: 'GET', querySchema: { q: 'token symbol or address' }, free: true },
    popularity: 99,
    verified: true,
  },
  {
    sourceId: 'free-jupiter-price',
    slug: 'free:jupiter-price',
    name: 'Jupiter Price API',
    description: 'Real-time Solana token prices via Jupiter aggregator. Free public API. GET ?ids=<mint,mint>',
    category: 'crypto',
    endpointUrl: 'https://lite-api.jup.ag/price/v3',
    websiteUrl: 'https://station.jup.ag/docs/apis/price-api',
    protocol: 'http',
    protocols: ['http'],
    pricePerQuery: 0,
    priceCurrency: 'USD',
    tags: ['free', 'solana', 'price', 'jupiter', 'test'],
    metadata: { provider: 'Jupiter', method: 'GET', querySchema: { ids: 'comma-separated mint addresses' }, free: true },
    popularity: 98,
    verified: true,
  },
  {
    sourceId: 'free-coingecko-ping',
    slug: 'free:coingecko-ping',
    name: 'CoinGecko Ping',
    description: 'Public CoinGecko API health check. Free, no auth. Use for testing agent connectivity.',
    category: 'crypto',
    endpointUrl: 'https://api.coingecko.com/api/v3/ping',
    websiteUrl: 'https://www.coingecko.com/en/api/documentation',
    protocol: 'http',
    protocols: ['http'],
    pricePerQuery: 0,
    priceCurrency: 'USD',
    tags: ['free', 'crypto', 'health', 'test'],
    metadata: { provider: 'CoinGecko', method: 'GET', free: true },
    popularity: 90,
    verified: true,
  },
  {
    sourceId: 'free-httpbin',
    slug: 'free:httpbin',
    name: 'httpbin Echo',
    description: 'Echoes back the request — perfect for testing agent key, headers, and request format. Always free.',
    category: 'utility',
    endpointUrl: 'https://httpbin.org/anything',
    websiteUrl: 'https://httpbin.org',
    protocol: 'http',
    protocols: ['http'],
    pricePerQuery: 0,
    priceCurrency: 'USD',
    tags: ['free', 'test', 'utility', 'echo', 'debug'],
    metadata: { provider: 'httpbin', method: 'POST', free: true },
    popularity: 70,
    verified: true,
  },
  {
    sourceId: 'mpp32-intelligence',
    slug: 'curated:mpp32-intelligence',
    name: 'MPP32 Intelligence Oracle',
    description: 'Real-time Solana token alpha score, rug risk, whale activity, smart money signals. M32 holders save up to 40%.',
    category: 'token-scanner',
    endpointUrl: '/api/intelligence',
    websiteUrl: 'https://mpp32.org/oracle',
    protocol: 'x402',
    protocols: ['x402', 'tempo', 'acp', 'ap2', 'agtp'],
    network: 'solana',
    asset: 'USDC',
    pricePerQuery: 0.008,
    priceCurrency: 'USD',
    scheme: 'exact',
    tags: ['solana', 'crypto', 'intelligence', 'whale', 'rug-risk', 'alpha'],
    metadata: { provider: 'MPP32', m32Discount: true },
    popularity: 100,
    verified: true,
  },
  // MCP servers — registry-discoverable, free public services
  {
    sourceId: 'mcp:filesystem',
    slug: 'mcp:filesystem',
    name: 'MCP Filesystem',
    description: 'Read/write files on the local filesystem via Model Context Protocol. Used by Claude Desktop, Cursor.',
    category: 'mcp-tool',
    endpointUrl: 'npx://@modelcontextprotocol/server-filesystem',
    websiteUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem',
    protocol: 'mcp',
    protocols: ['mcp'],
    pricePerQuery: 0,
    priceCurrency: 'USD',
    tags: ['mcp', 'filesystem', 'tool', 'official'],
    metadata: { transport: 'stdio', official: true },
    popularity: 100,
    verified: true,
  },
  {
    sourceId: 'mcp:github',
    slug: 'mcp:github',
    name: 'MCP GitHub',
    description: 'Read repos, issues, PRs, files via GitHub API through MCP. Official Anthropic server.',
    category: 'mcp-tool',
    endpointUrl: 'npx://@modelcontextprotocol/server-github',
    websiteUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/github',
    protocol: 'mcp',
    protocols: ['mcp'],
    pricePerQuery: 0,
    priceCurrency: 'USD',
    tags: ['mcp', 'github', 'tool', 'official', 'dev'],
    metadata: { transport: 'stdio', official: true },
    popularity: 100,
    verified: true,
  },
  {
    sourceId: 'mcp:postgres',
    slug: 'mcp:postgres',
    name: 'MCP Postgres',
    description: 'Query Postgres databases via MCP — schema introspection and read-only queries.',
    category: 'mcp-tool',
    endpointUrl: 'npx://@modelcontextprotocol/server-postgres',
    websiteUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/postgres',
    protocol: 'mcp',
    protocols: ['mcp'],
    pricePerQuery: 0,
    priceCurrency: 'USD',
    tags: ['mcp', 'postgres', 'sql', 'database', 'official'],
    metadata: { transport: 'stdio', official: true },
    popularity: 95,
    verified: true,
  },
  {
    sourceId: 'mcp:slack',
    slug: 'mcp:slack',
    name: 'MCP Slack',
    description: 'Send messages, read channels, list users via Slack API through MCP.',
    category: 'mcp-tool',
    endpointUrl: 'npx://@modelcontextprotocol/server-slack',
    websiteUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/slack',
    protocol: 'mcp',
    protocols: ['mcp'],
    pricePerQuery: 0,
    priceCurrency: 'USD',
    tags: ['mcp', 'slack', 'chat', 'tool', 'official'],
    metadata: { transport: 'stdio', official: true },
    popularity: 90,
    verified: true,
  },
  {
    sourceId: 'mcp:brave-search',
    slug: 'mcp:brave-search',
    name: 'MCP Brave Search',
    description: 'Web search via Brave Search API through Model Context Protocol.',
    category: 'mcp-tool',
    endpointUrl: 'npx://@modelcontextprotocol/server-brave-search',
    websiteUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/brave-search',
    protocol: 'mcp',
    protocols: ['mcp'],
    pricePerQuery: 0,
    priceCurrency: 'USD',
    tags: ['mcp', 'search', 'web', 'tool', 'official'],
    metadata: { transport: 'stdio', official: true },
    popularity: 95,
    verified: true,
  },
  {
    sourceId: 'mcp:puppeteer',
    slug: 'mcp:puppeteer',
    name: 'MCP Puppeteer',
    description: 'Browser automation, screenshots, web scraping via Puppeteer through MCP.',
    category: 'mcp-tool',
    endpointUrl: 'npx://@modelcontextprotocol/server-puppeteer',
    websiteUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/puppeteer',
    protocol: 'mcp',
    protocols: ['mcp'],
    pricePerQuery: 0,
    priceCurrency: 'USD',
    tags: ['mcp', 'browser', 'scraping', 'automation'],
    metadata: { transport: 'stdio', official: true },
    popularity: 90,
    verified: true,
  },
  {
    sourceId: 'mcp:fetch',
    slug: 'mcp:fetch',
    name: 'MCP Fetch',
    description: 'Fetch URLs and convert HTML to markdown for LLM consumption via MCP.',
    category: 'mcp-tool',
    endpointUrl: 'npx://@modelcontextprotocol/server-fetch',
    websiteUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/fetch',
    protocol: 'mcp',
    protocols: ['mcp'],
    pricePerQuery: 0,
    priceCurrency: 'USD',
    tags: ['mcp', 'fetch', 'http', 'web', 'official'],
    metadata: { transport: 'stdio', official: true },
    popularity: 95,
    verified: true,
  },
  {
    sourceId: 'mcp:memory',
    slug: 'mcp:memory',
    name: 'MCP Memory',
    description: 'Persistent knowledge graph memory for agents via MCP — entities, relations, observations.',
    category: 'mcp-tool',
    endpointUrl: 'npx://@modelcontextprotocol/server-memory',
    websiteUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/memory',
    protocol: 'mcp',
    protocols: ['mcp'],
    pricePerQuery: 0,
    priceCurrency: 'USD',
    tags: ['mcp', 'memory', 'knowledge-graph', 'agent', 'official'],
    metadata: { transport: 'stdio', official: true },
    popularity: 88,
    verified: true,
  },
  {
    sourceId: 'mcp:gdrive',
    slug: 'mcp:gdrive',
    name: 'MCP Google Drive',
    description: 'Search and read Google Drive files through MCP — Docs, Sheets, Slides.',
    category: 'mcp-tool',
    endpointUrl: 'npx://@modelcontextprotocol/server-gdrive',
    websiteUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/gdrive',
    protocol: 'mcp',
    protocols: ['mcp'],
    pricePerQuery: 0,
    priceCurrency: 'USD',
    tags: ['mcp', 'gdrive', 'google', 'docs', 'official'],
    metadata: { transport: 'stdio', official: true },
    popularity: 85,
    verified: true,
  },
  {
    sourceId: 'mcp:sqlite',
    slug: 'mcp:sqlite',
    name: 'MCP SQLite',
    description: 'Query and manipulate SQLite databases through MCP. Local-first, no server needed.',
    category: 'mcp-tool',
    endpointUrl: 'npx://@modelcontextprotocol/server-sqlite',
    websiteUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/sqlite',
    protocol: 'mcp',
    protocols: ['mcp'],
    pricePerQuery: 0,
    priceCurrency: 'USD',
    tags: ['mcp', 'sqlite', 'sql', 'database', 'official'],
    metadata: { transport: 'stdio', official: true },
    popularity: 88,
    verified: true,
  },
  {
    sourceId: 'mcp:time',
    slug: 'mcp:time',
    name: 'MCP Time',
    description: 'Current time, timezone conversion, date arithmetic via MCP.',
    category: 'mcp-tool',
    endpointUrl: 'npx://@modelcontextprotocol/server-time',
    websiteUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/time',
    protocol: 'mcp',
    protocols: ['mcp'],
    pricePerQuery: 0,
    priceCurrency: 'USD',
    tags: ['mcp', 'time', 'utility', 'official'],
    metadata: { transport: 'stdio', official: true },
    popularity: 80,
    verified: true,
  },
  {
    sourceId: 'mcp:gitlab',
    slug: 'mcp:gitlab',
    name: 'MCP GitLab',
    description: 'GitLab API access via MCP — projects, issues, MRs, CI/CD pipelines.',
    category: 'mcp-tool',
    endpointUrl: 'npx://@modelcontextprotocol/server-gitlab',
    websiteUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/gitlab',
    protocol: 'mcp',
    protocols: ['mcp'],
    pricePerQuery: 0,
    priceCurrency: 'USD',
    tags: ['mcp', 'gitlab', 'dev', 'official'],
    metadata: { transport: 'stdio', official: true },
    popularity: 75,
    verified: true,
  },
  {
    sourceId: 'mcp:everart',
    slug: 'mcp:everart',
    name: 'MCP EverArt',
    description: 'AI image generation across multiple models (FLUX, SDXL, etc.) via MCP.',
    category: 'mcp-tool',
    endpointUrl: 'npx://@modelcontextprotocol/server-everart',
    websiteUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/everart',
    protocol: 'mcp',
    protocols: ['mcp'],
    pricePerQuery: 0,
    priceCurrency: 'USD',
    tags: ['mcp', 'image-gen', 'art', 'official'],
    metadata: { transport: 'stdio', official: true },
    popularity: 80,
    verified: true,
  },
  {
    sourceId: 'mcp:sentry',
    slug: 'mcp:sentry',
    name: 'MCP Sentry',
    description: 'Read errors, issues, performance data from Sentry through MCP.',
    category: 'mcp-tool',
    endpointUrl: 'npx://@modelcontextprotocol/server-sentry',
    websiteUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/sentry',
    protocol: 'mcp',
    protocols: ['mcp'],
    pricePerQuery: 0,
    priceCurrency: 'USD',
    tags: ['mcp', 'sentry', 'monitoring', 'errors', 'official'],
    metadata: { transport: 'stdio', official: true },
    popularity: 78,
    verified: true,
  },
  {
    sourceId: 'mcp:notion',
    slug: 'mcp:notion',
    name: 'MCP Notion',
    description: 'Read and edit Notion pages, databases, blocks via MCP.',
    category: 'mcp-tool',
    endpointUrl: 'npx://@notionhq/notion-mcp-server',
    websiteUrl: 'https://github.com/makenotion/notion-mcp-server',
    protocol: 'mcp',
    protocols: ['mcp'],
    pricePerQuery: 0,
    priceCurrency: 'USD',
    tags: ['mcp', 'notion', 'docs', 'productivity'],
    metadata: { transport: 'stdio', official: true, vendor: 'Notion' },
    popularity: 90,
    verified: true,
  },
  {
    sourceId: 'mcp:linear',
    slug: 'mcp:linear',
    name: 'MCP Linear',
    description: 'Read issues, projects, cycles from Linear through MCP. Vendor-official.',
    category: 'mcp-tool',
    endpointUrl: 'npx://@linear/mcp-server',
    websiteUrl: 'https://linear.app/changelog/2025-mcp',
    protocol: 'mcp',
    protocols: ['mcp'],
    pricePerQuery: 0,
    priceCurrency: 'USD',
    tags: ['mcp', 'linear', 'project-management', 'vendor-official'],
    metadata: { transport: 'stdio', vendorOfficial: true, vendor: 'Linear' },
    popularity: 88,
    verified: true,
  },
  {
    sourceId: 'mcp:cloudflare',
    slug: 'mcp:cloudflare',
    name: 'MCP Cloudflare',
    description: 'Manage Cloudflare Workers, KV, R2, D1, Durable Objects via MCP. Vendor-official.',
    category: 'mcp-tool',
    endpointUrl: 'npx://@cloudflare/mcp-server-cloudflare',
    websiteUrl: 'https://github.com/cloudflare/mcp-server-cloudflare',
    protocol: 'mcp',
    protocols: ['mcp'],
    pricePerQuery: 0,
    priceCurrency: 'USD',
    tags: ['mcp', 'cloudflare', 'workers', 'edge', 'vendor-official'],
    metadata: { transport: 'stdio', vendorOfficial: true, vendor: 'Cloudflare' },
    popularity: 90,
    verified: true,
  },
  {
    sourceId: 'mcp:stripe',
    slug: 'mcp:stripe',
    name: 'MCP Stripe',
    description: 'Stripe payments, customers, subscriptions, invoices via MCP. Vendor-official.',
    category: 'mcp-tool',
    endpointUrl: 'npx://@stripe/mcp',
    websiteUrl: 'https://github.com/stripe/agent-toolkit',
    protocol: 'mcp',
    protocols: ['mcp'],
    pricePerQuery: 0,
    priceCurrency: 'USD',
    tags: ['mcp', 'stripe', 'payments', 'vendor-official'],
    metadata: { transport: 'stdio', vendorOfficial: true, vendor: 'Stripe' },
    popularity: 92,
    verified: true,
  },
  {
    sourceId: 'mcp:supabase',
    slug: 'mcp:supabase',
    name: 'MCP Supabase',
    description: 'Manage Supabase Postgres, Auth, Storage via MCP. Vendor-official.',
    category: 'mcp-tool',
    endpointUrl: 'npx://@supabase/mcp-server-supabase',
    websiteUrl: 'https://github.com/supabase-community/supabase-mcp',
    protocol: 'mcp',
    protocols: ['mcp'],
    pricePerQuery: 0,
    priceCurrency: 'USD',
    tags: ['mcp', 'supabase', 'database', 'vendor-official'],
    metadata: { transport: 'stdio', vendorOfficial: true, vendor: 'Supabase' },
    popularity: 88,
    verified: true,
  },
]

export const curatedSeedCrawler: Crawler = {
  source: 'curated-seed',
  description: 'Hand-picked, verified entries across x402 ecosystem and MCP registry',
  async run() {
    return { source: 'curated-seed', items: CURATED }
  },
}
